In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('iris.csv')
df

5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [3]:
df.describe()

5.1         3.5         1.4         0.2
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [4]:
df.shape

(149, 5)

In [5]:
df.columns

Index(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype='object')

In [6]:
df.rename(columns = {'sepal.length':'0','sepal.width':'1','petal.length':'2','petal.width':'3','variety':'4'}, inplace = True)

In [7]:
df.columns=['0','1','2','3','4']

In [8]:
df.columns

Index(['0', '1', '2', '3', '4'], dtype='object')

In [9]:
df

0    1    2    3               4
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

IDENTIFYING INDEPENDENT AND DEPENDENT FEATURES

In [10]:
print(df['4'].value_counts())

4
Iris-versicolor    50
Iris-virginica     50
Iris-setosa        49
Name: count, dtype: int64


In [11]:
X=df.iloc[:,:4]
Y=df.iloc[:,4]
print("X:\n---------------------\n{}".format(X))
print("Y:\n---------------------\n{}".format(Y))

X:
---------------------
       0    1    2    3
0    4.9  3.0  1.4  0.2
1    4.7  3.2  1.3  0.2
2    4.6  3.1  1.5  0.2
3    5.0  3.6  1.4  0.2
4    5.4  3.9  1.7  0.4
..   ...  ...  ...  ...
144  6.7  3.0  5.2  2.3
145  6.3  2.5  5.0  1.9
146  6.5  3.0  5.2  2.0
147  6.2  3.4  5.4  2.3
148  5.9  3.0  5.1  1.8

[149 rows x 4 columns]
Y:
---------------------
0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
144    Iris-virginica
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
Name: 4, Length: 149, dtype: object


SPLITTING TRAINING AND TESTING DATASET

In [12]:
from pandas.core.common import random_state
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,random_state=0)

In [13]:
print("X_train :\n{}".format(X_train))
print("X_train Shape:{}".format(X_train.shape))

X_train :
       0    1    2    3
51   6.9  3.1  4.9  1.5
2    4.6  3.1  1.5  0.2
146  6.5  3.0  5.2  2.0
10   4.8  3.4  1.6  0.2
56   4.9  2.4  3.3  1.0
..   ...  ...  ...  ...
9    5.4  3.7  1.5  0.2
103  6.5  3.0  5.8  2.2
67   6.2  2.2  4.5  1.5
117  7.7  2.6  6.9  2.3
47   5.3  3.7  1.5  0.2

[111 rows x 4 columns]
X_train Shape:(111, 4)


In [14]:
print("X_test :\n{}".format(X_test))
print("X_test Shape:{}".format(X_test.shape))

X_test :
       0    1    2    3
133  6.1  2.6  5.6  1.4
109  6.5  3.2  5.1  2.0
59   5.0  2.0  3.5  1.0
80   5.5  2.4  3.7  1.0
7    4.4  2.9  1.4  0.2
104  7.6  3.0  6.6  2.1
140  6.9  3.1  5.1  2.3
95   5.7  2.9  4.2  1.3
118  6.0  2.2  5.0  1.5
84   6.0  3.4  4.5  1.6
33   4.9  3.1  1.5  0.1
44   4.8  3.0  1.4  0.3
54   5.7  2.8  4.5  1.3
24   5.0  3.0  1.6  0.2
37   4.4  3.0  1.3  0.2
132  6.3  2.8  5.1  1.5
111  6.8  3.0  5.5  2.1
73   6.4  2.9  4.3  1.3
16   5.1  3.5  1.4  0.3
45   5.1  3.8  1.6  0.2
40   4.5  2.3  1.3  0.3
8    4.9  3.1  1.5  0.1
85   6.7  3.1  4.7  1.5
22   5.1  3.3  1.7  0.5
62   6.1  2.9  4.7  1.4
94   5.7  3.0  4.2  1.2
90   6.1  3.0  4.6  1.4
26   5.2  3.5  1.5  0.2
43   5.1  3.8  1.9  0.4
134  7.7  3.0  6.1  2.3
27   5.2  3.4  1.4  0.2
97   5.1  2.5  3.0  1.1
96   6.2  2.9  4.3  1.3
69   5.9  3.2  4.8  1.8
18   5.1  3.8  1.5  0.3
105  4.9  2.5  4.5  1.7
136  6.4  3.1  5.5  1.8
61   6.0  2.2  4.0  1.0
X_test Shape:(38, 4)


In [15]:
print("Y_train :\n{}".format(Y_train))
print("Y_train Shape:{}".format(Y_train.shape))

Y_train :
51     Iris-versicolor
2          Iris-setosa
146     Iris-virginica
10         Iris-setosa
56     Iris-versicolor
            ...       
9          Iris-setosa
103     Iris-virginica
67     Iris-versicolor
117     Iris-virginica
47         Iris-setosa
Name: 4, Length: 111, dtype: object
Y_train Shape:(111,)


In [16]:
print("Y_test :\n{}".format(Y_test))
print("Y_test Shape:{}".format(Y_test.shape))

Y_test :
133     Iris-virginica
109     Iris-virginica
59     Iris-versicolor
80     Iris-versicolor
7          Iris-setosa
104     Iris-virginica
140     Iris-virginica
95     Iris-versicolor
118     Iris-virginica
84     Iris-versicolor
33         Iris-setosa
44         Iris-setosa
54     Iris-versicolor
24         Iris-setosa
37         Iris-setosa
132     Iris-virginica
111     Iris-virginica
73     Iris-versicolor
16         Iris-setosa
45         Iris-setosa
40         Iris-setosa
8          Iris-setosa
85     Iris-versicolor
22         Iris-setosa
62     Iris-versicolor
94     Iris-versicolor
90     Iris-versicolor
26         Iris-setosa
43         Iris-setosa
134     Iris-virginica
27         Iris-setosa
97     Iris-versicolor
96     Iris-versicolor
69     Iris-versicolor
18         Iris-setosa
105     Iris-virginica
136     Iris-virginica
61     Iris-versicolor
Name: 4, dtype: object
Y_test Shape:(38,)


APPLYING THT MODEL

FITTING KNN MODEL TO THE DATA SET

In [17]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train,Y_train)
Y_pred=knn.predict(X_test)

In [18]:
print("Y_pred:\n------------------------\n{}".format(Y_pred))

Y_pred:
------------------------
['Iris-virginica' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor']


In [19]:
print("Y_test:\n------------------------\n{}".format(Y_test))

Y_test:
------------------------
133     Iris-virginica
109     Iris-virginica
59     Iris-versicolor
80     Iris-versicolor
7          Iris-setosa
104     Iris-virginica
140     Iris-virginica
95     Iris-versicolor
118     Iris-virginica
84     Iris-versicolor
33         Iris-setosa
44         Iris-setosa
54     Iris-versicolor
24         Iris-setosa
37         Iris-setosa
132     Iris-virginica
111     Iris-virginica
73     Iris-versicolor
16         Iris-setosa
45         Iris-setosa
40         Iris-setosa
8          Iris-setosa
85     Iris-versicolor
22         Iris-setosa
62     Iris-versicolor
94     Iris-versicolor
90     Iris-versicolor
26         Iris-setosa
43         Iris-setosa
134     Iris-virginica
27         Iris-setosa
97     Iris-versicolor
96     Iris-versicolor
69     Iris-versicolor
18         Iris-setosa
105     Iris-virginica
136     Iris-virginica
61     Iris-versicolor
Name: 4, dtype: object


CONFUSION MATRIX

In [20]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(confusion_matrix(Y_test,Y_pred))
accuracy=accuracy_score(Y_test,Y_pred)*100
print("Accuracy of the model is {:.2f}".format(accuracy))

[[14  0  0]
 [ 0 13  1]
 [ 0  3  7]]
Accuracy of the model is 89.47


NEW FEATURE

In [21]:
X_new=np.array([[2.3,2.9,5.0,1.9]])
print("X_new.shape: {}".format(X_new.shape))

X_new.shape: (1, 4)


In [ ]:
Y_new=knn.predict(X_new)

In [23]:
print("Prediction : {}".format(Y_new))
print("Predicted Target Name : {}".format(Y_new))

Prediction : ['Iris-versicolor']
Predicted Target Name : ['Iris-versicolor']
